### ISSUE TITLE
Bag of Holding Crashes

### ISSUE THREAD

**Issue by Sethervan** [NamrocSmith/NamrocsBagOfHolding#2]
I'd really like to use this mod along with Magica but I can't seem to get it running at all.  In fact if I try to run this mod by itself it crashes.  Other people are obviously using it so there must be something I'm missing, like a requirement.  I've reviewed the curse page and your wiki but nothing shows additional requirements that I may be missing.  I'll attach the crash log when I try to run with just this mod.
[crash-2017-02-12_08.47.14-client.txt](https://github.com/NamrocSmith/NamrocsBagOfHolding/files/769445/crash-2017-02-12_08.47.14-client.txt)

**Comment by NamrocSmith** [comment]
Looks like the auto builder didn't mark this correct.  CompatLayer is a required not optional:

https://mods.curse.com/mc-mods/minecraft/253729-compatlayer

Add that and give it a go.

**Comment by Sethervan** [comment]
Awesome.  I tested i and CompatLayer seems to make it work.  Can't wait to try out the mods!  Thanks for the quick reply too!
