### ISSUE TITLE
No icon for BFF or Magica Journal

### ISSUE THREAD

**Issue by Zygus42** [NamrocSmith/NamrocsBagOfHolding#3]
Magica-1.10.2-1.0.1-release
compatlayer-1.10-0.2.2
NamrocsBagOfHolding-1.10.2-1.1.12-release
forge-1.10.2-12.18.3.2254-installer-win

Both the BFF and the Magica Journal of Larz Smith are just a collection of pink and purple squares.  They work, but are not very esthetic.

**Comment by NamrocSmith** [comment]
This should be handled in the 11.2 releases
